# Generated by Django 4.0.3 on 2022-03-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('ram', models.CharField(max_length=40)),
                ('rom', models.CharField(max_length=40)),
                ('SSD', models.CharField(max_length=40)),
                ('HDD', models.CharField(max_length=40)),
                ('weight', models.CharField(max_length=40)),
                ('year', models.DateTimeField()),
            ],
        ),
    ]
